name: Run Test

on: [pull_request]

jobs:
  # test build success
  Build:
    name: Build
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Test
      run: xcodebuild -project CLabFinal.xcodeproj -scheme CLabFinal -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13'
